# Application name
spring.application.name=coreerp

# Server
server.port=8081

# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/coreerp_db
spring.datasource.username=root
spring.datasource.password=tysonwith1tiger

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
